name: PUBLISH

on:
  push:
    tags:
      - v*

jobs:


  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements-package.txt

      - name: Build
        run: |
          python3 setup.py sdist bdist_wheel

      - name: Publish
        env: # Or as an environment variable
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m twine upload -u "__token__" -p $PYPI_TOKEN dist/*
